---
title: "Publication"
---


```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE
)
```


Updated on `r Sys.Date()`. Papers are sorted by research directions and publication dates.  #corresponding author, \*co-first author。

<style>
ul {
	list-style-type: decimal;
}
li {
    display: list-item;
    text-align: -webkit-match-parent;
    unicode-bidi: isolate;
}
</style>

### Bioinformatics Software

- **Zuguang Gu#**, [simona: a comprehensive R package for semantic similarity analysis on bio-ontologies](https://doi.org/10.1186/s12864-024-10759-4). _BMC genomics_ 2024.
- Noriaki Sato, Yao-Zhong Zhang, **Zuguang Gu**, Seiya Imoto, [biotextgraph: graphical summarization of functional similarities from textual information](https://doi.org/10.1093/bioinformatics/btae357). _Bioinformatics_ 2024.
- **Zuguang Gu#**, Daniel Hübschmann, [rGREAT: an R/bioconductor package for functional enrichment on genomic regions](https://doi.org/10.1093/bioinformatics/btac745). _Bioinformatics_ 2023.
- **Zuguang Gu#**, Daniel Hübschmann, [simplifyEnrichment: A Bioconductor Package for Clustering and Visualizing Functional Enrichment Results](https://doi.org/10.1016/j.gpb.2022.04.008). _Genomics, Proteomics & Bioinformatics_ 2023.
- **Zuguang Gu#**, [Complex heatmap visualization](https://doi.org/10.1002/imt2.43). _iMeta_ 2022.
- **Zuguang Gu#**, Daniel Hübschmann, [Improve consensus partitioning via a hierarchical procedure](https://doi.org/10.1093/bib/bbac048). _Briefings in Bioinformatics_ 2022.
- **Zuguang Gu#**, Daniel Hübschmann, [Make Interactive Complex Heatmaps in R](https://doi.org/10.1093/bioinformatics/btab806). _Bioinformatics_ 2022.
- **Zuguang Gu#**, Daniel Hübschmann, [spiralize: an R package for visualizing data on spirals](https://doi.org/10.1093/bioinformatics/btab778). _Bioinformatics_ 2022.
- **Zuguang Gu#**, Matthias Schlesner, Daniel Hübschmann, [cola: an R/Bioconductor package for consensus partitioning through a general framework](https://doi.org/10.1093/nar/gkaa1146). _Nucleic Acids Research_ 2021.
- Daniel Hübschmann, Lea Jopp-Saile, Carolin Andresen, Stephen Krämer, **Zuguang Gu**, Christoph E Heilig, Simon Kreutzfeldt, Veronica Teleanu, Stefan Fröhling, Roland Eils, Matthias Schlesner, [Analysis of mutational signatures with yet another package for signature analysis](https://doi.org/10.1002/gcc.22918). _Genes, Chromosomes & Cancer_ 2021.
- **Zuguang Gu#**, Roland Eils, Matthias Schlesner, Naveed Ishaque, [EnrichedHeatmap: an R/Bioconductor package for comprehensive visualization of genomic signal associations](https://doi.org/10.1186/s12864-018-4625-x). _BMC Genomics_ 2018.
- **Zuguang Gu**, Roland Eils, Matthias Schlesner, [Complex heatmaps reveal patterns and correlations in multidimensional genomic data](https://doi.org/10.1093/bioinformatics/btw313). _Bioinformatics_ 2016.
- **Zuguang Gu**, Roland Eils, Matthias Schlesner, [HilbertCurve: an R/Bioconductor package for high-resolution visualization of genomic data](https://doi.org/10.1093/bioinformatics/btw161). _Bioinformatics_ 2016.
- **Zuguang Gu**, Roland Eils, Matthias Schlesner, [gtrellis: an R/Bioconductor package for making genome-level Trellis graphics](https://doi.org/10.1186/s12859-016-1051-4). _BMC Bioinformatics_ 2016.
- **Zuguang Gu**, Lei Gu, Roland Eils, Matthias Schlesner, Benedikt Brors, [circlize Implements and enhances circular visualization in R](https://doi.org/10.1093/bioinformatics/btu393). _Bioinformatics_ 2014.
- **Zuguang Gu**, Jin Wang, [CePa: an R package for finding significant pathways weighted by multiple network centralities](https://doi.org/10.1093/bioinformatics/btt008). _Bioinformatics_ 2013.
- **Zuguang Gu**, Jialin Liu, Kunming Cao, Junfeng Zhang, Jin Wang, [Centrality-based pathway enrichment: a systematic approach for finding significant pathways dominated by key genes](https://doi.org/10.1186/1752-0509-6-56). _BMC Systems Biology_ 2012.
- **Zuguang Gu**, Jie Li, Song Gao, Ming Gong, Junling Wang, Hua Xu, Chenyu Zhang, Jin Wang, [InterMitoBase: an annotated database and analysis platform of protein-protein interactions for human mitochondria](
https://doi.org/10.1186/1471-2164-12-335). _BMC Genomics_ 2011.


### Computational Geometry

- **Zuguang Gu#**, [Construction, Transformation and Structures of 2x2 Space-Filling Curves](https://doi.org/10.48550/arXiv.2412.16962). _arXiv_ 2024.

### Software Engineering

- **Zuguang Gu#**, [On the dependency heaviness of CRAN/Bioconductor ecosystem](https://doi.org/10.1016/j.jss.2023.111610). _Journal of Systems and Software_ 2023.
- **Zuguang Gu#**, Daniel Hübschmann, [Pkgndep: a tool for analyzing dependency heaviness of R packages](https://doi.org/10.1093/bioinformatics/btac449). _Bioinformatics_ 2022.

### Bibliometrics

- **Zuguang Gu#**, [Two separated worlds: On the preference of influence in life science and biomedical research](https://doi.org/10.1016/j.joi.2025.101641). _Journal of Informetrics_ 2025.


### Omics and Precision Medicine

- Xiaoping Zou, Shuang Nie, Jing Cao, Mengyue Shi, Kathleen Schuck, Zhao Shi, Lingling Zhang, Hongzhen Li, Yifeng Sun, Chao Fang, Jingxiong Hu, Yiqi Niu, Yuanyuan Yu, Zhiheng Zhang, Chao Li, Mingyue Hu, Lei Wang, Kuirong Jiang, Zipeng Lu, Jan Akkan, Susanne Raulefs, Christoph Kahlert, Susanne Roth, Ingrid Herr, Yuan Wan, Andre Mihaljevic, Xuetian Qian, Qi Zhang, Maggie Haitian Wang, Jörg Kleeff, Helmut Friess, **Zuguang Gu**, Christoph W Michalski, Shanshan Shen, Bo Kong, [ALDH1A3 promotes aggressive basal-like pancreatic cancer through an AP-1/RUNX2 enhancer network](https://doi.org/10.1038/s41388-025-03530-w). _Oncogene_ 2025.
- Dominik Vonficht, Lea Jopp-Saile, Schayan Yousefian, Viktoria Flore, Inés Simó Vesperinas, Ruth Teuber, Bogdan Avanesyan, Yanjiang Luo, Caroline Röthemeier, Florian Grünschläger, Mirian Fernandez-Vaquero, Vincent Fregona, Diana Ordoñez-Rueda, Laura K Schmalbrock, Luca Deininger, Angelo Jovin Yamachui Sitcheu, **Zuguang Gu**, Maja C Funk, Ralf Mikut, Mathias Heikenwälder, Angelika Eggert, Arend von Stackelberg, Sebastian Kobold, Jan Krönke, Ulrich Keller, Andreas Trumpp, Ahmed N Hegazy, Cornelia Eckert, Daniel Hübschmann, Simon Haas, [Ultra-high-scale cytometry-based cellular interaction mapping](https://doi.org/10.1038/s41592-025-02744-w). _Nature Methods_ 2025.
- Stephanie Gehrs\*, **Zuguang Gu\***, Joschka Hey, Dieter Weichenhan, Niklas Buckwalter, Moritz Jakab, Agnes Hotz-Wagenblatt, Kersten Breuer, Maria Llamazares Prada, Daniel Hübschmann, Katharina Schlereth, Christoph Plass, Hellmut Augustin, [DNMT3A-dependent DNA methylation shapes the endothelial enhancer landscape](https://doi.org/10.1093/nar/gkaf435). _Nucleic Acids Research_ 2025.
- Andreas Betz, Hao-En Huang, **Zuguang Gu**, Ombretta Colasanti, Teng-Feng Li, Jasper Hesebeck-Brinckmann, Nadine Gillich, Gnimah Eva Gnouamozi, Matthias Schlesner, Florian WR Vondran, Stephan Urban, Ralf Bartenschlager, Marco Binder, Volker Lohmann, [Reconstitution of interferon regulatory factor 7 expression restores interferon beta induction in Huh7 cells](https://doi.org/10.1128/jvi.00703-25). _Journal of Virology_ 2025.
- Stephanie Gehrs, Moritz Jakab, Ewgenija Gutjahr, **Zuguang Gu**, Dieter Weichenhan, Jan-Philipp Mallm, Carolin Mogler, Matthias Schlesner, Christoph Plass, Katharina Schlereth, Hellmut G Augustin, [The spatial zonation of the murine placental vasculature is specified by epigenetic mechanisms](https://doi.org/10.1016/j.devcel.2024.12.037). _Developmental Cell_ 2025.
- Josefine Radke, Naveed Ishaque, Randi Koll, **Zuguang Gu**, Elisa Schumann, Lina Sieverling, Sebastian Uhrig, Daniel Hübschmann, Umut H Toprak, Cristina López, Xavier Pastor Hostench, Simone Borgoni, Dilafruz Juraeva, Fabienne Pritsch, Nagarajan Paramasivam, Gnana Prakash Balasubramanian, Matthias Schlesner, Shashwat Sahay, Marc Weniger, Debora Pehl, Helena Radbruch, Anja Osterloh, Agnieszka Korfel, Martin Misch, Julia Onken, Katharina Faust, Peter Vajkoczy, Dag Moskopp, Yawen Wang, Andreas Jödicke, Lorenz Trümper, Ioannis Anagnostopoulos, Dido Lenze, Ralf Küppers, Michael Hummel, Clemens A Schmitt, Otmar D Wiestler, Stephan Wolf, Andreas Unterberg, Roland Eils, Christel Herold-Mende, Benedikt Brors, Reiner Siebert, Stefan Wiemann, Frank L Heppner, [The genomic and transcriptional landscape of primary central nervous system lymphoma](https://doi.org/10.1038/s41467-022-30050-y). _Nature Communications_ 2022.
- Marina Laplana, Matthias Bieg, Christian Faltus, Svitlana Melnik, Olga Bogatyrova, **Zuguang Gu**, Thomas Muley, Michael Meister, Hendrik Dienemann, Esther Herpel, Christopher I Amos, Matthias Schlesner, Roland Eils, Christoph Plass, Angela Risch, [Differentially methylated regions within lung cancer risk loci are enriched in deregulated enhancers](https://doi.org/10.1080/15592294.2021.1878723). _Epigenetics_ 2022.
- Mengyu Tu, Lukas Klein, Elisa Espinet, Theodoros Georgomanolis, Florian Wegwitz, Xiaojuan Li, Laura Urbach, Adi Danieli-Mackay, Stefan Küffer, Kamil Bojarczuk, Athanasia Mizi, Ufuk Günesdogan, Björn Chapuy, **Zuguang Gu**, Albrecht Neesse, Uday Kishore, Philipp Ströbel, Elisabeth Hessmann, Stephan A Hahn, Andreas Trumpp, Argyris Papantonis, Volker Ellenrieder, Shiv K Singh, [TNF-α-producing macrophages determine subtype identity and prognosis via AP1 enhancer reprogramming in pancreatic cancer](https://doi.org/10.1038/s43018-021-00258-w). _Nature Cancer_ 2021.
- Ana Maia, **Zuguang Gu**, André Koch, Mireia Berdiel-Acer, Rainer Will, Matthias Schlesner, Stefan Wiemann, [IFNβ1 secreted by breast cancer cells undergoing chemotherapy reprograms stromal fibroblasts to support tumour growth after treatment](https://doi.org/10.1002/1878-0261.12905). Molecular oncology 2021.
- Nina Hensel\*, **Zuguang Gu\***, Sagar\*, Dominik Wieland, Katharina Jechow, Janine Kemming, Sian Llewellyn-Lacey, Emma Gostick, Oezlem Sogukpinar, Florian Emmerich, David A Price, Bertram Bengsch, Tobias Boettler, Christoph Neumann-Haefelin, Roland Eils, Christian Conrad, Ralf Bartenschlager, Dominic Grün, Naveed Ishaque, Robert Thimme, Maike Hofmann, [Memory-like HCV-specific CD8+ T cells retain a molecular scar after cure of chronic HCV infection](https://doi.org/10.1038/s41590-020-00817-w). _Nature Immunology_ 2021.
- Elisa Espinet#, **Zuguang Gu\***, Charles D Imbusch\*, Nathalia A Giese, Magdalena Büscher, Mariam Safavi, Silke Weisenburger, Corinna Klein, Vanessa Vogel, Mattia Falcone, Jacob Insua-Rodríguez, Manuel Reitberger, Vera Thiel, Steffi O Kossi, Alexander Muckenhuber, Karnjit Sarai, Alex Y L Lee, Elyne Backx, Soheila Zarei, Matthias M Gaida, Manuel Rodríguez-Paredes, Elisa Donato, Hsi-Yu Yen, Roland Eils, Matthias Schlesner, Nicole Pfarr, Thilo Hackert, Christoph Plass, Benedikt Brors, Katja Steiger, Dieter Weichenhan, H Efsun Arda, Ilse Rooman, Janel L Kopp, Oliver Strobel, Wilko Weichert, Martin R Sprick, Andreas Trumpp, [Aggressive PDACs Show Hypomethylation of Repetitive Elements and the Execution of an Intrinsic IFN Program Linked to a Ductal Cell of Origin](https://doi.org/10.1158/2159-8290.CD-20-1202). _Cancer Discovery_ 2021.
- Yonghe Wu\*, Michael Fletcher\*, **Zuguang Gu\***, Qi Wang, Barbara Costa, Anna Bertoni, Ka-Hou Man, Magdalena Schlotter, Jörg Felsberg, Jasmin Mangei, Martje Barbus, Ann-Christin Gaupel, Wei Wang, Tobias Weiss, Roland Eils, Michael Weller, Haikun Liu, Guido Reifenberger, Andrey Korshunov, Peter Angel, Peter Lichter, Carl Herrmann, Bernhard Radlwimmer, [Glioblastoma epigenome profiling identifies SOX10 as a master regulator of molecular tumour subtype](https://doi.org/10.1038/s41467-020-20225-w). _Nature Communications_ 2020.
- Simon Raffel, Daniel Klimmeck, Mattia Falcone, Aykut Demir, Alireza Pouya, Petra Zeisberger, Christoph Lutz, Marco Tinelli, Oliver Bischel, Lars Bullinger, Christian Thiede, Anne Flörcken, Jörg Westermann, Gerhard Ehninger, Anthony D Ho, Carsten Müller-Tidow, **Zuguang Gu**, Carl Herrmann, Jeroen Krijgsveld, Andreas Trumpp, Jenny Hansson, [Quantitative proteomics reveals specific metabolic features of acute myeloid leukemia stem cells](https://doi.org/10.1182/blood.2019003654). _Blood_ 2020.
- Enoch B Antwi, Ada Olins, Vladimir B Teif, Matthias Bieg, Tobias Bauer, **Zuguang Gu**, Benedikt Brors, Roland Eils, Donald Olins, Naveed Ishaque, [Whole-genome fingerprint of the DNA methylome during chemically induced differentiation of the human AML cell line HL-60/S4](https://doi.org/10.1242/bio.044222). _Biology Open_ 2020.
- Maike Smits, Katharina Zoldan, Naveed Ishaque, **Zuguang Gu**, Katharina Jechow, Dominik Wieland, Christian Conrad, Roland Eils, Catherine Fauvelle, Thomas F Baumert, Florian Emmerich, Bertram Bengsch, Christoph Neumann-Haefelin, Maike Hofmann, Robert Thimme, Tobias Boettler, [Follicular T helper cells shape the HCV-specific CD4+ T cell repertoire after virus elimination](https://doi.org/10.1172/JCI129642). _The Journal of Clinical Investigation_ 2020.
- Stephan M Tirier, Jeongbin Park, Friedrich Preußer, Lisa Amrhein, **Zuguang Gu**, Simon Steiger, Jan-Philipp Mallm, Teresa Krieger, Marcel Waschow, Björn Eismann, Marta Gut, Ivo G Gut, Karsten Rippe, Matthias Schlesner, Fabian Theis, Christiane Fuchs, Claudia R Ball, Hanno Glimm, Roland Eils, Christian Conrad, [Pheno-seq - linking visual features and gene expression in 3D cell culture systems](https://doi.org/10.1038/s41598-019-48771-4). _Scientific Reports_ 2019.
- Calvin Wing Yiu Chan, **Zuguang Gu**, Matthias Bieg, Roland Eils, Carl Herrmann, [Impact of cancer mutational signatures on transcription factor motifs in the human genome](https://doi.org/10.1186/s12920-019-0525-4). _BMC Medical Genomics_ 2019.
- Nagarajan Paramasivam, Daniel Hübschmann, Umut H Toprak, Naveed Ishaque, Marian Neidert, Daniel Schrimpf, Damian Stichel, David Reuss, Philipp Sievers, Annekathrin Reinhardt, Annika K Wefers, David T W Jones, **Zuguang Gu**, Johannes Werner, Sebastian Uhrig, Hans-Georg Wirsching, Matthias Schick, Melanie Bewerunge-Hudler, Katja Beck, Stephanie Brehmer, Steffi Urbschat, Marcel Seiz-Rosenhagen, Daniel Hänggi, Christel Herold-Mende, Ralf Ketter, Roland Eils, Zvi Ram, Stefan M Pfister, Wolfgang Wick, Michael Weller, Rachel Grossmann, Andreas von Deimling, Matthias Schlesner, Felix Sahm, [Mutational patterns and regulatory networks in epigenetic subgroups of meningioma](https://doi.org/10.1007/s00401-019-02008-w). _Acta Neuropathologica_ 2019.
- Verena Körber, Jing Yang, Pankaj Barah, Yonghe Wu, Damian Stichel, **Zuguang Gu**, Michael Nai Chung Fletcher, David Jones, Bettina Hentschel, Katrin Lamszus, Jörg Christian Tonn, Gabriele Schackert, Michael Sabel, Jörg Felsberg, Angela Zacher, Kerstin Kaulich, Daniel Hübschmann, Christel Herold-Mende, Andreas von Deimling, Michael Weller, Bernhard Radlwimmer, Matthias Schlesner, Guido Reifenberger, Thomas Höfer, Peter Lichter, [Evolutionary Trajectories of IDHWT Glioblastomas Reveal a Common Path of Early Tumorigenesis Instigated Years ahead of Initial Diagnosis](https://doi.org/10.1016/j.ccell.2019.02.007). _Cancer Cell_ 2019.
- Naveed Ishaque, Mohammed L Abba, Christine Hauser, Nitin Patil, Nagarajan Paramasivam, Daniel Huebschmann, Jörg Hendrik Leupold, Gnana Prakash Balasubramanian, Kortine Kleinheinz, Umut H Toprak, Barbara Hutter, Axel Benner, Anna Shavinskaya, Chan Zhou, **Zuguang Gu**, Jules Kerssemakers, Alexander Marx, Marcin Moniuszko, Miroslaw Kozlowski, Joanna Reszec, Jacek Niklinski, Jürgen Eils, Matthias Schlesner, Roland Eils, Benedikt Brors, Heike Allgayer, [Whole genome sequencing puts forward hypotheses on metastasis evolution and therapy in colorectal cancer](https://doi.org/10.1016/j.ccell.2019.02.007). _Nature Communications_ 2018.
- Daniel B Lipka, Tania Witte, Reka Toth, Jing Yang, Manuel Wiesenfarth, Peter Nöllke, Alexandra Fischer, David Brocks, **Zuguang Gu**, Jeongbin Park, Brigitte Strahm, Marcin Wlodarski, Ayami Yoshimi, Rainer Claus, Michael Lübbert, Hauke Busch, Melanie Boerries, Mark Hartmann, Maximilian Schönung, Umut Kilik, Jens Langstein, Justyna A Wierzbinska, Caroline Pabst, Swati Garg, Albert Catalá, Barbara De Moerloose, Michael Dworzak, Henrik Hasle, Franco Locatelli, Riccardo Masetti, Markus Schmugge, Owen Smith, Jan Stary, Marek Ussowicz, Marry M van den Heuvel-Eibrink, Yassen Assenov, Matthias Schlesner, Charlotte Niemeyer, Christian Flotho, Christoph Plass, [RAS-pathway mutation patterns define epigenetic subclasses in juvenile myelomonocytic leukemia](https://doi.org/10.1038/s41467-017-02177-w). _Nature Communications_ 2017.
- Paul A Northcott, Ivo Buchhalter, A Sorana Morrissy, Volker Hovestadt, Joachim Weischenfeldt, Tobias Ehrenberger, Susanne Gröbner, Maia Segura-Wang, Thomas Zichner, Vasilisa A Rudneva, Hans-Jörg Warnatz, Nikos Sidiropoulos, Aaron H Phillips, Steven Schumacher, Kortine Kleinheinz, Sebastian M Waszak, Serap Erkek, David T W Jones, Barbara C Worst, Marcel Kool, Marc Zapatka, Natalie Jäger, Lukas Chavez, Barbara Hutter, Matthias Bieg, Nagarajan Paramasivam, Michael Heinold, **Zuguang Gu**, Naveed Ishaque, Christina Jäger-Schmidt, Charles D Imbusch, Alke Jugold, Daniel Hübschmann, Thomas Risch, Vyacheslav Amstislavskiy, Francisco German Rodriguez Gonzalez, Ursula D Weber, Stephan Wolf, Giles W Robinson, Xin Zhou, Gang Wu, David Finkelstein, Yanling Liu, Florence M G Cavalli, Betty Luu, Vijay Ramaswamy, Xiaochong Wu, Jan Koster, Marina Ryzhova, Yoon-Jae Cho, Scott L Pomeroy, Christel Herold-Mende, Martin Schuhmann, Martin Ebinger, Linda M Liau, Jaume Mora, Roger E McLendon, Nada Jabado, Toshihiro Kumabe, Eric Chuah, Yussanne Ma, Richard A Moore, Andrew J Mungall, Karen L Mungall, Nina Thiessen, Kane Tse, Tina Wong, Steven J M Jones, Olaf Witt, Till Milde, Andreas Von Deimling, David Capper, Andrey Korshunov, Marie-Laure Yaspo, Richard Kriwacki, Amar Gajjar, Jinghui Zhang, Rameen Beroukhim, Ernest Fraenkel, Jan O Korbel, Benedikt Brors, Matthias Schlesner, Roland Eils, Marco A Marra, Stefan M Pfister, Michael D Taylor, Peter Lichter, [The whole-genome landscape of medulloblastoma subtypes](https://doi.org/10.1038/nature22973). _Nature_ 2017.
- Marcus Winter, Loreen Thürmann, **Zuguang Gu**, Gerrit Schüürmann, Gunda Herberth, Denise Hinz, Martin von Bergen, Hauke Harms, Sven Olek, Stefan Röder, Michael Borte, Roland Eils, Irina Lehmann, Saskia Trump, [The benzene metabolite 1,4-benzoquinone reduces regulatory T-cell function: A potential mechanism for tobacco smoke-associated atopic dermatitis](https://doi.org/10.1016/j.jaci.2017.01.034). _The Journal of Allergy and Clinical Immunology_ 2017.
- Kortine Kleinheinz, Isabell Bludau, Daniel Hübschmann, Michael Heinold, Philip Kensche, **Zuguang Gu**, Cristina López, Michael Hummel, Wolfram Klapper, Peter Möller, Inga Vater, Rabea Wagener, Benedikt Brors, Reiner Siebert, Roland Eils, Matthias Schlesner, [ACEseq–allele specific copy number estimation from whole genome sequencing](https://doi.org/10.1101/210807). _BioRXiv_ 2017.
- Saskia Trump, Matthias Bieg, **Zuguang Gu**, Loreen Thürmann, Tobias Bauer, Mario Bauer, Naveed Ishaque, Stefan Röder, Lei Gu, Gunda Herberth, Christian Lawerenz, Michael Borte, Matthias Schlesner, Christoph Plass, Nicolle Diessl, Markus Eszlinger, Oliver Mücke, Horst-Dietrich Elvers, Dirk K Wissenbach, Martin von Bergen, Carl Herrmann, Dieter Weichenhan, Rosalind J Wright, Irina Lehmann, Roland Eils, [Prenatal maternal stress and wheeze in children: novel insights into epigenetic regulation](https://doi.org/10.1038/srep28616). _Scientific Reports_ 2016.
- Tobias Bauer, Saskia Trump, Naveed Ishaque, Loreen Thürmann, Lei Gu, Mario Bauer, Matthias Bieg, **Zuguang Gu**, Dieter Weichenhan, Jan-Philipp Mallm, Stefan Röder, Gunda Herberth, Eiko Takada, Oliver Mücke, Marcus Winter, Kristin M Junge, Konrad Grützmann, Ulrike Rolle-Kampczyk, Qi Wang, Christian Lawerenz, Michael Borte, Tobias Polte, Matthias Schlesner, Michaela Schanne, Stefan Wiemann, Christina Geörg, Hendrik G Stunnenberg, Christoph Plass, Karsten Rippe, Junichiro Mizuguchi, Carl Herrmann, Roland Eils, Irina Lehmann, [Environment-induced epigenetic reprogramming in genomic regulatory elements in smoking mothers and their children](https://doi.org/10.15252/msb.20156520). _Molecular Systems Biology_ 2016.
- Jenny Wegert, Naveed Ishaque, Romina Vardapour, Christina Geörg, **Zuguang Gu**, Matthias Bieg, Barbara Ziegler, Sabrina Bausenwein, Nasenien Nourkami, Nicole Ludwig, Andreas Keller, Clemens Grimm, Susanne Kneitz, Richard D Williams, Tas Chagtai, Kathy Pritchard-Jones, Peter van Sluis, Richard Volckmann, Jan Koster, Rogier Versteeg, Tomas Acha, Maureen J O’Sullivan, Peter K Bode, Felix Niggli, Godelieve A Tytgat, Harm van Tinteren, Marry M van den Heuvel-Eibrink, Eckart Meese, Christian Vokuhl, Ivo Leuschner, Norbert Graf, Roland Eils, Stefan M Pfister, Marcel Kool, Manfred Gessler, [Mutations in the SIX1/2 pathway and the DROSHA/DGCR8 miRNA microprocessor complex underlie high-risk blastemal type Wilms tumors](https://doi.org/10.1016/j.ccell.2015.01.002). _Cancer Cell_ 2015.
- Lei Gu, Sandra C Frommel, Christopher C Oakes, Ronald Simon, Katharina Grupp, Cristina Y Gerig, Dominik Bär, Mark D Robinson, Constance Baer, Melanie Weiss, **Zuguang Gu**, Matthieu Schapira, Ruprecht Kuner, Holger Sültmann, Maurizio Provenzano, Marie-Laure Yaspo, Benedikt Brors, Jan Korbel, Thorsten Schlomm, Guido Sauter, Roland Eils, Christoph Plass, Raffaella Santoro, [BAZ2A (TIP5) is involved in epigenetic alterations in prostate cancer and its overexpression predicts disease recurrence](https://doi.org/10.1038/ng.3165). _Nature Genetics_ 2015.

### Other Topics

- Federico Vita, Cosimo Taiti, Antonio Pompeiano, **Zuguang Gu**, Emilio Lo Presti, Larisa Whitney, Michele Monti, Giuseppe Di Miceli, Dario Giambalvo, Paolo Ruisi, Lorenzo Guglielminetti, Stefano Mancuso, [Aromatic and proteomic analyses corroborate the distinction between Mediterranean landraces and modern varieties of durum wheat](https://doi.org/10.1038/srep34619). _Scientific Reports_ 2016.
- Chenfeng He, Ying-Xin Li, Guangxin Zhang, **Zuguang Gu**, Rong Yang, Jie Li, Zhi John Lu, Zhi-Hua Zhou, Chenyu Zhang, Jin Wang, [MiRmat: mature microRNA sequence prediction](https://doi.org/10.1371/journal.pone.0051673). _PloS One_ 2012.
- **Zuguang Gu**, Chenyu Zhang, Jin Wang, [Gene regulation is governed by a core network in hepatocellular carcinoma](https://doi.org/10.1186/1752-0509-6-32). BMC systems biology 2012.
- Lingyun Zhu, Qiang Wang, Lin Zhang, Zhixiang Fang, Fang Zhao, Zhiyuan Lv, **Zuguang Gu**, Junfeng Zhang, Jin Wang, Ke Zen, Yang Xiang, Dongjin Wang, Chen-Yu Zhang, [Hypoxia induces PGC-1α expression and mitochondrial biogenesis in the myocardium of TOF patients](https://doi.org/10.1038/cr.2010.46). _Cell Research_ 2010.

