---
title: sfcurve
---


```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.width = 8,
    fig.height = 8
)
```

$n \times n$ space-filling curves.

### Basic

<div id="soft-info">

软件包 | 链接 
:------ | :----------
Language | R, C++
CRAN | https://cran.r-project.org/package=sfcurve
GitHub | https://github.com/jokergoo/sfcurve
Documentation | https://jokergoo.github.io/sfcurve/
Publication | Zuguang Gu, [Construction, Transformation and Structures of 2x2 Space-Filling Curves](https://doi.org/10.48550/arXiv.2412.16962). _arXiv_ 2024.


</div>

### Example

2x2 curve

```{r}
library(sfcurve)
p = sfc_2x2("I", "2222", rot = 270)
p
plot(p)
```

3x3 Peano curve

```{r}
p = sfc_3x3_peano("I", "1111")
plot(p)
```

Initialized by a simple curve

```{r}
p = sfc_seed("LLLILILIILIILIIILIIILIIII")
p2 = sfc_2x2(p, "1111")
plot(p2)
```

<script>
$( function() {
    $("table thead").css("display", "none");
} );
</script>
